### ISSUE TITLE
导入原版hoshino时由于和harubot的config文件不同而引发错误

### ISSUE THREAD

**Issue by taomohappy** [Soung2279/NANA7MI_REC#1]
https://github.com/Soung2279/NANA7MI_REC/blob/f7cf1c23cb5c6863d8b631538cefe5bb029633b4/nana7mi_record.py#L29-L30

原版hoshino里的config是不包含`FORWARD_MSG_NAME`和`FORWARD_MSG_UID`这两个参数的，导入时会引发错误，建议删除这两行（我看函数里也没用到），或者在readme里标明是harubot专属

**Comment by Soung2279** [comment]
已经更改了。感谢issue
